---
- name: create prometheus group
  group:
    name: prometheus
    state: present

- name: add prometheus user
  user:
    name: prometheus
    group: prometheus
    create_home: no
    shell: /usr/sbin/nologin
