---
- name: Wait for system ready
  hosts: all
  gather_facts: yes
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: prometheus
  hosts: prometheus
  gather_facts: yes
  become: yes
  roles:
  - prometheus

- name: nginx-auth
  hosts: prometheus
  become: yes
  strategy: free
  roles:
  - nginx-auth  
