---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: validator
  hosts: validator
  become: yes
  roles:
  - polkadot-validator

- name: nginx-auth
  hosts: validator
  become: yes
  strategy: free
  roles:
  - nginx-auth  

- name: node-exporter
  hosts: validator
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: node_exporter_enabled|bool }

- name: prometheus
  hosts: prometheus
  become: yes
  roles:
  - { role: prometheus, when: prometheus_enabled|bool }

- name: nginx-auth
  hosts: prometheus
  become: yes
  strategy: free
  roles:
  - nginx-auth  

# This is needed to break the circular dependency (validator needs to allow access to prometheus machine only on 9091, prometheus needs to configure the validator IP)
- name: validator_allow_prometheus_port
  hosts: validator
  become: yes
  tasks:
    - include_vars:
        file: roles/polkadot-validator/defaults/main.yml
    - { include: roles/polkadot-validator/tasks/firewall_prometheus.yml, when: prometheus_enabled|bool }
